version: '3.7'
services:
  ciclozero_prod:
    image: butlerhat/ciclozero_prod:latest
    container_name: ciclozero_prod
    user: vscode
    init: true
    volumes:
      - ${HOST_HOME}/.cloudflared:/home/vscode/.cloudflared:cached
      - ${HOST_HOME}/data/CicloZero/results:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/results:cached
      - ${HOST_HOME}/data/CicloZero/downloads:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/downloads:cached
      - ${HOST_HOME}/data/CicloZero/data:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/data:cached
      - ${HOST_HOME}/urjc_chapo/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/robotframework/keywords/woocommerce_files:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/robotframework/keywords/woocommerce_files:cached
      - cron_volume:/var/spool/cron/crontabs:cached
      - cookies_volume:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/browser/user_data_dir:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    restart: unless-stopped
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
    command: bash .devcontainer/postCreateCommand.sh

volumes:
  cron_volume:
    driver: local

  cookies_volume:
    driver: local

networks:
  external:
    name: net_robot
