version: '3.7'
services:
  ciclozero_prod:
    build:
      image: butlerhat/kitdigital-prod
      context: ../..
      # Dockerfile is relative to context
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PYPI_USER: ${PYPI_USER}
        PYPI_PASS: ${PYPI_PASS}
      target: prod
