version: '3.7'
services:
  kitdigital_prod:
    image: butlerhat/kitdigital-prod
    build:
      context: ../..
      # Dockerfile is relative to context
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PYPI_USER: ${PYPI_USER}
        PYPI_PASS: ${PYPI_PASS}
      target: prod
