apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitdigital-prod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitdigital-prod
  template:
    metadata:
      labels:
        app: kitdigital-prod
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data && chmod -R 755 /data"]
        volumeMounts:
        - name: kitdigital-storage
          mountPath: /data
        securityContext:
          runAsUser: 0  # Run as root for permission changes
      containers:
      - name: kitdigital-prod
        image: butlerhat/kitdigital-prod
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000  # vscode user ID
          runAsGroup: 1000 # vscode group ID
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            memory: "500Mi"
            cpu: "0.2"
        volumeMounts:
        - name: kitdigital-storage
          mountPath: /workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/result_kit
      volumes:
      - name: kitdigital-storage
        persistentVolumeClaim:
          claimName: kitdigital-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: kitdigital-prod-service
  namespace: default
spec:
  selector:
    app: kitdigital-prod
  ports:
  - name: streamlit
    protocol: TCP
    port: 8501
    targetPort: 8501


# Connect with cloudflare
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared-deployment-kitdigital-prod
  name: cloudflared-deployment-kitdigital-prod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared-deployment-kitdigital-prod
  template:
    metadata:
      labels:
        pod: cloudflared-deployment-kitdigital-prod
    spec:
      containers:
      - command:
        - cloudflared
        - tunnel
        - --metrics
        - 0.0.0.0:2000
        - run
        args:
        - --token
        - $(TUNNEL-TOKEN)
        image: cloudflare/cloudflared:latest
        name: cloudflared-kitdigital-prod
        env:
        - name: TUNNEL-TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token-kitdigital-iframe-prod
              key: token
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "0.2"
        livenessProbe:
          httpGet:
          # Cloudflared has a /ready endpoint which returns 200 if and only if
          # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitdigital-pv
  namespace: default
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/kitdigital
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitdigital-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi