[paths]
logo_path = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/static/logo.png"
robot = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/robotframework"
result_kit = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/result_kit"
excel_template = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/static/template_data.xlsx"
word_template = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/static/Plantilla.docx"
accessibility_excel = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/static/informe_accesibilidad.xlsx"
firebase_secrets = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/.streamlit/paypaya-platform-firebase-adminsdk-brtic-fef459e6f4.json"
justificacion_multi_dir = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/KitDigital/web/static/justificacion_multi"

[urls]
orchestrator = "http://api-orchestrator-service:8000"